### ISSUE TITLE
Unable to install: No valid exports main found

### ISSUE THREAD

**Issue by fabiosangregorio** [dragonwocky/notion-enhancer#92]
Installing notion-enhancer (as administrator) results in an error. Complete log below.

* Platform: win10
* node js version: v13.5.0
* enhancer version: v0.8.5

```powershell
C:\WINDOWS\system32>npm i -g notion-enhancer

> notion-enhancer@0.8.5 preuninstall C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer
> node bin.js remove -y

internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\node_modules\cac'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\bin.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
npm WARN lifecycle notion-enhancer@0.8.5~preuninstall: continuing anyway notion-enhancer@0.8.5 preuninstall: `node bin.js remove -y`
npm WARN lifecycle Exit status 1
C:\Users\fabio\AppData\Roaming\npm\notion-enhancer -> C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\bin.js

> notion-enhancer@0.8.5 postinstall C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer
> node bin.js apply -y

internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\node_modules\cac'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\bin.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notion-enhancer@0.8.5 postinstall: `node bin.js apply -y`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the notion-enhancer@0.8.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fabio\AppData\Roaming\npm-cache\_logs\2020-09-08T16_30_37_060Z-debug.log

C:\WINDOWS\system32>
```

**Comment by dragonwocky** [comment]
have you previously attempted installing it?

**Comment by fabiosangregorio** [comment]
Yes, I had the previous version installed and I removed it following the guide. 
Unfortunately I wasn't able to install it with the above commands. Npm logs can be found here: https://pastebin.com/fLYkkig3
And CLI log can be found below.

```cmd
C:\WINDOWS\system32>npm remove -g notion-enhancer --force
npm WARN using --force I sure hope you know what you are doing.
up to date in 0.134s

C:\WINDOWS\system32>npm i -g notion-enhancer
npm ERR! code EEXIST
npm ERR! path C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\bin.js
npm ERR! dest C:\Users\fabio\AppData\Roaming\npm\notion-enhancer.cmd
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer\bin.js' -> 'C:\Users\fabio\AppData\Roaming\npm\notion-enhancer.cmd'
npm ERR! File exists: C:\Users\fabio\AppData\Roaming\npm\notion-enhancer.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fabio\AppData\Roaming\npm-cache\_logs\2020-09-09T05_10_05_650Z-debug.log
```

I also went around and manually deleted "C:\Users\fabio\AppData\Roaming\npm\notion-enhancer.cmd" with the same result.
Using `--force` at the install results in the error of the first post on this issue.

**Comment by dragonwocky** [comment]
try also manually deleting `C:\Users\fabio\AppData\Roaming\npm\node_modules\notion-enhancer`

**Comment by fabiosangregorio** [comment]
I tried that too, but no luck with that. I have this problem only on my Surface Pro. On my other pc it works fine.

**Comment by dragonwocky** [comment]
hm, odd.
only things i can think of are either reinstalling node or using yarn - I'm on a surface pro too and found npm occasionally problematic, but have had no such issues since I started using https://yarnpkg.com/

**Comment by fabiosangregorio** [comment]
Reinstalling node did the trick. That was weird ahaha
Thank you for your time and for the awesome package!
