### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by xinsu626** [dragonwocky/notion-enhancer#98]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
when I run `sudo npm i -g notion-enhancer`, I got the following error.

```
=== NOTION ENHANCEMENT LOG ===
### ERROR ###
[Error: EACCES: permission denied, mkdir '/var/root/.notion-enhancer'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/root/.notion-enhancer'
}
=== END OF LOG ===
```

**expected behaviour**
why is this a bug - what should be happening?

I expect it will be installed successfully. Since I ran the command under root.

**screenshots**
if applicable, add screenshots of your problem.

I have copied and pasted the error message above.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
I am using macOS catalina, 10.15.6.

**Comment by florinme** [comment]
Same issue also on Catalina 10.15.6.

**Comment by tonyshutov** [comment]
macOS Catalina 10.15.7 bug still present. 

trying to install with/without root results in the same EACCES error:
[2020-10-14T17_56_54_159Z-debug.log](https://github.com/dragonwocky/notion-enhancer/files/5380051/2020-10-14T17_56_54_159Z-debug.log)

under user:
```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/notion-enhancer
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/notion-enhancer
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/notion-enhancer'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/notion-enhancer'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/notion-enhancer'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

under root:
```
### ERROR ###
Error: EACCES: permission denied, mkdir '/Applications/Notion.app/Contents/Resources/app'
    at Object.mkdirSync (fs.js:921:3)
    at Object.promisified.mkdirpSync (/usr/local/lib/node_modules/notion-enhancer/node_modules/asar/lib/wrapped-fs.js:24:38)
    at module.exports.extractAll (/usr/local/lib/node_modules/notion-enhancer/node_modules/asar/lib/asar.js:177:6)
    at module.exports (/usr/local/lib/node_modules/notion-enhancer/pkg/apply.js:57:5)
    at async CAC.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/bin.js:29:5) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/Applications/Notion.app/Contents/Resources/app'
}
=== END OF LOG ===
```

**Comment by dragonwocky** [comment]
@tonyshutov that's a different error. Same error code, different path - the original error was a bug, this is just a user installation issue. Run these commands to fix it (and don't do the `npm i -g notion-enhancer` under root).
```
sudo chmod -R a+wr /usr/local/lib/node_modules
sudo chmod -R a+wr /usr/local/bin
sudo chmod -R a+wr /Applications/Notion/Contents/Resources
sudo chmod -R a+wr /Applications/Notion.app/Contents/Resources
```
